name: Deploy DAGs

on:
  push:
    branches:
      - main

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_USER_HOST: ${{ secrets.SSH_USER_HOST }}
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ env.SSH_PRIVATE_KEY }}

    - name: Sync requirements.txt and install Python packages
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./requirements.txt ${{ env.SSH_USER_HOST }}:/root/airflow/requirements.txt \
        && ssh -o StrictHostKeyChecking=no ${{ env.SSH_USER_HOST }} "source /root/airflow/.venv/bin/activate && pip install -r /root/airflow/requirements.txt"

    - name: Sync Dags Folder
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./dags ${{ env.SSH_USER_HOST }}:/root/airflow/dags
         
      
